### PR TITLE
Release/1J00_1700

### PR DESCRIPTION
**Pull request by rsjoyner**
## Summary

 Updated to newest version of the CART LDD; 1J00_1970
 Updated to IM version 1.20.00

### CODE REVIEW

**Review by lylehuber — COMMENTED** [review]
Should say PDS4_CASSINI_1J00_1700 somewhere?

**Comment by jordanpadams** [comment]
@lylehuber @rsjoyner missing update to `pds4_versions.txt` file to include 1J00 version

**Comment by jordanpadams** [comment]
Screenshot 2024-03-21 at 10 13 32 AM

**Comment by jordanpadams** [comment]
@lylehuber @rsjoyner If this is a bug in LDDTool, we can open a ticket over there.

**Comment by rsjoyner** [comment]
Yes.  I think this is a bug in LDDTool.   I will work with Steve to make sure that I am not doing something way stupid in the LDDTOOL command.

**Comment by jordanpadams** [comment]
@rsjoyner do you need to include the CART LDD as well since the schematron references it?

**Comment by jordanpadams** [comment]
@rsjoyner that is the issue... do the CART LDD needs to be added to his repo.

https://pds-data-dictionaries.github.io/getting-started/ldd-repo-overview.html#handling-ldd-dependencies

**Comment by jordanpadams** [comment]
Let me know if you run into issues

**Comment by rsjoyner** [comment]
While we are waiting for Steve to reply.   See the enclosure for the edited version of the schematron file with the required fix.
Is there a way to use these files in lieu of the "build" ?

[CASSINI_LDD_1J00_1700_20240320.zip](https://github.com/pds-data-dictionaries/ldd-cassini/files/14705549/CASSINI_LDD_1J00_1700_20240320.zip)

**Comment by jordanpadams** [comment]
@rsjoyner @lylehuber this is not a bug in LDDTool:

```
lddtool -lpJ ldd-cassini/src/PDS4_CASSINI_IngestLDD.xml ldd-cart/src/PDS4_CART_IngestLDD.xml
```

So if we add that to the dependencies per the instructions above, the automation will work and the files will be accurate

**Comment by rsjoyner** [comment]
> lddtool -lpJ ldd-cassini/src/PDS4_CASSINI_IngestLDD.xml ldd-cart/src/PDS4_CART_IngestLDD.xml

1. I tried a functionally similar command on local copies of the 3 LDDs (e.g., cassini, cart, and geom):

lddtool_1E30_edited -lpJ1 -V 1J00 PDS4_CASSINI_IngestLDD.xml PDS4_CART_IngestLDD.xml PDS4_GEOM_IngestLDD.xml > log-a.txt

lddtool crashed again.

2. I tried again referencing only the 2 LDDs (e.g., cassini and cart) and lddtool crashed again).

I am using:

LDDTool Version: 14.3.0
Built with IM Version: 1.21.0.0
Build Date: 2023-09-18 21:33:49
Configured IM Versions: [1L00, 1K00, 1J00, 1I00, 1H00, 1G00, 1F00, 1E00, 1D00, 1C00, 1B10, 1B00]

**Comment by jordanpadams** [comment]
@lylehuber @rsjoyner this is fixed and ready for review/merge

**Review by lylehuber — APPROVED** [review]
I hope this works now.

**Comment by jordanpadams** [comment]
@lylehuber one minor update to remove an unnecessary submodule for ldd-geom.

**Comment by jordanpadams** [comment]
A fun first corner case of nested dependencies. Had to implement recursion to handle it. Throwback to Comp Sci 101

**Comment by jordanpadams** [comment]
@lylehuber I merged it for you. Once it [tags a release here](https://github.com/pds-data-dictionaries/ldd-cassini/releases), you can submit a ticket to get it put online.

**Pull request merged**
